In [2]:
import torch

In [3]:
# generate data
torch.manual_seed(7)

# generate features
features = torch.randn((1, 3))

# define size of each layer in this neural network
n_input = features.shape[1]     # number of input units (*must match number of input features)
n_hidden = 2                    # number of hidden units
n_output = 1                    # number of output units

# generate weights for inputs to hidden layer
W1 = torch.randn(n_input, n_hidden)

# generate weights for hidden layer to output layer
W2 = torch.randn(n_hidden, n_output)

#  create bias terms for hidden and output layers
B1 = torch.randn((1, n_hidden))
B2 = torch.randn((1, n_output))

### Exercise: Calculate the output for this multi-layer network using the weights W1, W2 and the biases B1, B2

In [3]:
features

tensor([[-0.1468,  0.7861,  0.9468]])

In [4]:
n_input

3

In [5]:
W1

tensor([[-1.1143,  1.6908],
        [-0.8948, -0.3556],
        [ 1.2324,  0.1382]])

In [6]:
W2

tensor([[-1.6822],
        [ 0.3177]])

In [9]:
B1

tensor([[0.1328, 0.1373]])

In [10]:
B2

tensor([[0.2405]])

Output equation:

$$\hat{y} = \sigma (w_1 x_1 + w_2 x_2 + ... + b)$$

In [7]:
def activation(x):
    return 1 / (1 + torch.exp(-x))

In [8]:
# calculate values for the hidden later
h = activation(torch.mm(features, W1) + B1)

# calculate values for output layer
output = activation(torch.mm(h, W2) + B2)
print(output)

tensor([[0.3171]])
