In [2]:
import torch
import numpy as np

In [3]:
a = np.random.rand(4, 3)
a

array([[0.99253809, 0.16149193, 0.6460443 ],
       [0.95803898, 0.19086791, 0.07442448],
       [0.50742786, 0.21442535, 0.66767737],
       [0.93732804, 0.66606384, 0.25198648]])

In [4]:
b = torch.from_numpy(a)
b

tensor([[0.9925, 0.1615, 0.6460],
        [0.9580, 0.1909, 0.0744],
        [0.5074, 0.2144, 0.6677],
        [0.9373, 0.6661, 0.2520]], dtype=torch.float64)

In [5]:
b.numpy()

array([[0.99253809, 0.16149193, 0.6460443 ],
       [0.95803898, 0.19086791, 0.07442448],
       [0.50742786, 0.21442535, 0.66767737],
       [0.93732804, 0.66606384, 0.25198648]])

--------------------------------------
The memory is shared between the Numpy array and the Torch tensor, so changing the values in-place of one will change the other

In [6]:
# multiply Tensor by 2, in place (denoted by underscore)
b.mul_(2)

tensor([[1.9851, 0.3230, 1.2921],
        [1.9161, 0.3817, 0.1488],
        [1.0149, 0.4289, 1.3354],
        [1.8747, 1.3321, 0.5040]], dtype=torch.float64)

In [7]:
# numpy array will now show the same changed values
a

array([[1.98507618, 0.32298387, 1.2920886 ],
       [1.91607795, 0.38173582, 0.14884896],
       [1.01485572, 0.4288507 , 1.33535475],
       [1.87465608, 1.33212768, 0.50397296]])