In [1]:
import torch

In [2]:
def activation(x):
    # sigmoid activation function
    return 1 / (1+torch.exp(-x))

In [3]:
# generate data
torch.manual_seed(7)

# create features
features = torch.randn((1, 5)) # randn creates tensor of normal dist variables
                               # tensor of 1 row, 5 elements

# create weights
weights = torch.randn_like(features) # creates tensor with same shape as 'features'

# create a bias term
bias = torch.randn((1,1))

Output (prediction) formula
$$\hat{y} = \sigma(w_1 x_1 + w_2 x_2 + ... + w_n x_n + b)$$

In [4]:
# calculate the output of this simple neural network using weight and bias tensors
y = activation(torch.sum(features * weights) + bias)
y

tensor([[0.1595]])

### A simpler approach to solving this problem:
#### Using matrix multiplication

In [5]:
# torch.mm() or torch.matmul()
torch.mm(features, weights)

RuntimeError: size mismatch, m1: [1 x 5], m2: [1 x 5] at c:\programdata\miniconda3\conda-bld\pytorch-cpu_1532498166916\work\aten\src\th\generic/THTensorMath.cpp:2070

There is a runtime error because we should have m1 [1 x 5] and m2 [5 x 1]

In [6]:
# need to change the shape of tensor 2, or weights, from 1x5 to 5x1
weights.reshape(5, 1)

tensor([[-0.8948],
        [-0.3556],
        [ 1.2324],
        [ 0.1382],
        [-1.6822]])

In [7]:
weights

tensor([[-0.8948, -0.3556,  1.2324,  0.1382, -1.6822]])

In [8]:
# we can now compute matrix multiplication with weights.reshape()
y = activation(torch.mm(features, weights.reshape(5, 1)) + bias)
y

tensor([[0.1595]])

In [9]:
# can also use view()
y = activation(torch.mm(features, weights.view(5, 1)) + bias)
y

tensor([[0.1595]])

In [10]:
# can also resize
weights.resize_(5, 1)

tensor([[-0.8948],
        [-0.3556],
        [ 1.2324],
        [ 0.1382],
        [-1.6822]])

In [11]:
weights

tensor([[-0.8948],
        [-0.3556],
        [ 1.2324],
        [ 0.1382],
        [-1.6822]])

In [12]:
# now we can directly call weights
y = activation(torch.mm(features, weights) + bias)
y

tensor([[0.1595]])